<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Downloadpdf</name>
   <tag></tag>
   <elementGuidId>1cc2102a-74ab-47bf-a796-7e4659d14ac1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='pdf']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#pdf</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Download Pdf&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>de1b74f2-cc55-47e8-855b-524bcac1c3ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pdf</value>
      <webElementGuid>967874d9-ba3d-4a52-96a8-f008681e672b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>assets/files/sample.pdf</value>
      <webElementGuid>6471db57-24a6-4008-8958-e3b6f5f57a91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>download</name>
      <type>Main</type>
      <value>sample.pdf</value>
      <webElementGuid>2c9f6a86-1f79-4193-9af7-cda4ffe82362</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Download Pdf</value>
      <webElementGuid>20ca6383-4820-4d6a-bda4-32665d794d66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pdf&quot;)</value>
      <webElementGuid>904b46b2-89d0-4402-b343-3be07118fe56</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='pdf']</value>
      <webElementGuid>1d5e67ca-bc95-40fb-b107-61f2e07825d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Download Pdf')]</value>
      <webElementGuid>91699663-9c6f-4717-9502-b598471c5161</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Download Excel'])[1]/following::a[1]</value>
      <webElementGuid>aa476918-18de-48fc-a459-94cd44c74a62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Download'])[1]/following::a[2]</value>
      <webElementGuid>8a73f6a6-d0a4-4b98-9080-57df0f3ec62a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Download Text'])[1]/preceding::a[1]</value>
      <webElementGuid>f92a1b69-6d4b-4d73-bc86-35bc5911cf48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='On completion of this exercise, you can learn the following concepts.'])[1]/preceding::a[2]</value>
      <webElementGuid>8f83c203-e8fe-4985-af67-92e28ca95eb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Download Pdf']/parent::*</value>
      <webElementGuid>57ac394e-7442-4f03-b6bf-288dabafce60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'assets/files/sample.pdf')]</value>
      <webElementGuid>1c29f6ab-fa8f-4a76-a913-94074fa61c35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]/a</value>
      <webElementGuid>c91181e8-f640-4155-aacf-d49a5c1e1e9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'pdf' and @href = 'assets/files/sample.pdf' and (text() = 'Download Pdf' or . = 'Download Pdf')]</value>
      <webElementGuid>131431df-1606-42aa-aa81-77890ef737c4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
