<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Alerttitle</name>
   <tag></tag>
   <elementGuidId>e413f138-3c70-4548-9feb-79ea1f78de42</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact'])[1]/following::h1[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h1.title.has-text-centered.is-pulled-left</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=heading[name=&quot;Alert&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>c1f9ce52-c1bc-4aad-abc5-0128f14cce6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>title has-text-centered is-pulled-left</value>
      <webElementGuid>3a5b76b0-045d-4f7d-a6ff-01d10a00ad83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Alert</value>
      <webElementGuid>ba6d2421-b417-4cbb-85a1-27a595c76c94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;has-navbar-fixed-top&quot;]/body[1]/app-root[@class=&quot;ng-tns-c490104382-0&quot;]/app-alert[@class=&quot;ng-star-inserted&quot;]/app-pageheader[1]/section[@class=&quot;section&quot;]/div[@class=&quot;container&quot;]/h1[@class=&quot;title has-text-centered is-pulled-left&quot;]</value>
      <webElementGuid>9f2e38e9-2262-40a7-9030-fb2e4710045e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact'])[1]/following::h1[1]</value>
      <webElementGuid>da255f02-eed6-4a14-a9c5-16489c942fa8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Courses'])[1]/following::h1[1]</value>
      <webElementGuid>15f4cf9e-e369-4deb-b5be-84b50b5580ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Accept the Alert'])[1]/preceding::h1[1]</value>
      <webElementGuid>8b98f1cc-1271-4283-b4c9-50581b489e58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Simple Alert'])[1]/preceding::h1[1]</value>
      <webElementGuid>21159ef9-9ca0-4b5c-871d-b951057ee623</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Alert']/parent::*</value>
      <webElementGuid>dbff58dc-bd66-4153-a2b9-b40eb721f625</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>1fbb045c-df78-43dc-98ff-f34dbb67c0d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'Alert' or . = 'Alert')]</value>
      <webElementGuid>344632aa-3a38-44e1-902f-e8a8709747aa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
