<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Fruits</name>
   <tag></tag>
   <elementGuidId>b31a72f6-c0e2-43cb-bb20-8f50a00463fe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='fruits']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#fruits</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#fruits</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>a227bc83-1992-4651-ada6-128d2c4140dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fruits</value>
      <webElementGuid>21bde8a9-9285-4158-8296-f2d82b37a360</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select FruitAppleMangoOrangeBananaPine Apple</value>
      <webElementGuid>65c9b3e7-042a-4782-ae9e-2fc27752747d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fruits&quot;)</value>
      <webElementGuid>29b7896a-dac9-47ae-87e2-011e9f82d2da</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='fruits']</value>
      <webElementGuid>283e2e4f-1339-4425-8564-09326ccb72a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select the apple using visible text'])[1]/following::select[1]</value>
      <webElementGuid>e50cf930-15b0-4477-9934-8f369878b5f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dropdown'])[1]/following::select[1]</value>
      <webElementGuid>48f35cff-0fa3-4a93-8dd4-6cb66fcd707d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select the last programming language and print all the options'])[1]/preceding::select[2]</value>
      <webElementGuid>93207898-f28e-4060-ae3c-4d6439db1a66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>b60b12be-6dd8-41bf-96d7-f0496c768c28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'fruits' and (text() = 'Select FruitAppleMangoOrangeBananaPine Apple' or . = 'Select FruitAppleMangoOrangeBananaPine Apple')]</value>
      <webElementGuid>0b9f724c-63d0-4184-8e87-113823a614cf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
