<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Multioption</name>
   <tag></tag>
   <elementGuidId>e8b8777a-1d1a-49d7-868a-f68b450add6b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='superheros']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#superheros</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#superheros</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>d5108a2d-28e1-49cf-be75-51835c5be741</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>superheros</value>
      <webElementGuid>82ce38de-b6e0-4e56-89f0-e5978daac3a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ant-ManAquamanThe AvengersBatmanBatwomanBlack PantherCaptain AmericaCaptain MarvelDaredevilDoc SavageDoctor StrangeElektraFantastic FourGhost RiderGreen LanternGuardians of the GalaxyHellboyIncredible HulkIron ManMarvelmanRobinThe ShadowSpider-ManSupergirlSupermanThorWolverineWonder Womane=&quot;xm&quot;X-Men</value>
      <webElementGuid>253099a7-ff21-4731-8df8-101004f1cd11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;superheros&quot;)</value>
      <webElementGuid>7906858d-dcb3-4373-81ca-8762fc4243b5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='superheros']</value>
      <webElementGuid>0ba4098d-6f4d-4817-8547-a5d1961afaea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select the apple using visible text'])[1]/following::select[2]</value>
      <webElementGuid>1a547a1b-40ec-4fe3-9cd0-d5c293509aa9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select the last programming language and print all the options'])[1]/preceding::select[1]</value>
      <webElementGuid>46e4e1ab-3118-4e42-b905-a8413954c782</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select India using value &amp; print the selected value'])[1]/preceding::select[2]</value>
      <webElementGuid>185a2c35-9340-4631-a0a7-fc161225e0e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/select</value>
      <webElementGuid>c12aa972-e86a-4eff-85f7-00fdbb6869dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'superheros' and (text() = 'Ant-ManAquamanThe AvengersBatmanBatwomanBlack PantherCaptain AmericaCaptain MarvelDaredevilDoc SavageDoctor StrangeElektraFantastic FourGhost RiderGreen LanternGuardians of the GalaxyHellboyIncredible HulkIron ManMarvelmanRobinThe ShadowSpider-ManSupergirlSupermanThorWolverineWonder Womane=&quot;xm&quot;X-Men' or . = 'Ant-ManAquamanThe AvengersBatmanBatwomanBlack PantherCaptain AmericaCaptain MarvelDaredevilDoc SavageDoctor StrangeElektraFantastic FourGhost RiderGreen LanternGuardians of the GalaxyHellboyIncredible HulkIron ManMarvelmanRobinThe ShadowSpider-ManSupergirlSupermanThorWolverineWonder Womane=&quot;xm&quot;X-Men')]</value>
      <webElementGuid>784b0982-5b95-4e0b-8e08-121ef5ce3df6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
