<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>programming language</name>
   <tag></tag>
   <elementGuidId>5d3c5cb4-4b7f-40a6-9fea-7f4a53a6e31a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='lang']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#lang</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#lang</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>67f221ae-104a-42ca-aed9-cbd34f722f58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lang</value>
      <webElementGuid>2ddb036d-f813-44eb-82a9-72e958b8a582</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>JavaScriptJavaPythonSwiftC#</value>
      <webElementGuid>51a2bebd-a82c-4bfc-802f-01f055e3daf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lang&quot;)</value>
      <webElementGuid>c7f65c26-e21a-4003-8d88-365d191529b2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='lang']</value>
      <webElementGuid>e30b5552-f2d6-47b0-a8ef-4be382d9b477</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select the last programming language and print all the options'])[1]/following::select[1]</value>
      <webElementGuid>78e2638b-129c-45c5-b019-c80af6267c04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select India using value &amp; print the selected value'])[1]/preceding::select[1]</value>
      <webElementGuid>03c942e1-276e-4c8d-a6cd-2a1ed3bed0e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Click me'])[1]/preceding::select[2]</value>
      <webElementGuid>7c23b310-a726-4f8e-b8b7-9f6b1ecad909</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/select</value>
      <webElementGuid>1ed5d06b-89ae-4608-83a0-b6e9cb8d31ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'lang' and (text() = 'JavaScriptJavaPythonSwiftC#' or . = 'JavaScriptJavaPythonSwiftC#')]</value>
      <webElementGuid>6c2f0e8f-d58c-4239-8799-b617de89ff7a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
