<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>moderalertbtn</name>
   <tag></tag>
   <elementGuidId>3afeb71c-87c6-4d5c-9755-70268051c459</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='modern']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#modern</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Modern Alert&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>44511fe9-9fbb-458b-ad7c-6d6f865f9983</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>modern</value>
      <webElementGuid>ffaa38aa-e37e-4a01-8f7c-6db37cf01414</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button is-success</value>
      <webElementGuid>fc82222f-aa16-43a5-8a8f-fc0fa79b3a3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Modern Alert</value>
      <webElementGuid>41a470af-7649-4de4-a6be-f0a45d8365d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modern&quot;)</value>
      <webElementGuid>0c08f158-4fe5-4367-afca-04deef8457c4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='modern']</value>
      <webElementGuid>d50876fe-c872-4623-9185-b2f86e9c9a21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sweet alert'])[1]/following::button[1]</value>
      <webElementGuid>3afccf03-4538-403a-838a-61ecbec9814f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Prompt Alert'])[1]/following::button[1]</value>
      <webElementGuid>8c22b8e2-fa91-4ead-abcf-ee814ade28d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='On completion of this exercise, you can learn the following concepts.'])[1]/preceding::button[2]</value>
      <webElementGuid>e355eafb-4b2d-4727-ba85-39e463d28462</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='switchTo()'])[1]/preceding::button[2]</value>
      <webElementGuid>1032d717-8b05-4132-b4aa-3bef1a9fcb6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Modern Alert']/parent::*</value>
      <webElementGuid>277c94c4-de9a-4e99-a3aa-dd44321f7cf4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/button</value>
      <webElementGuid>017689fa-a9e9-4294-8357-bed028caa68d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'modern' and (text() = 'Modern Alert' or . = 'Modern Alert')]</value>
      <webElementGuid>d0976e33-8b87-480b-aaa7-8bd3eef6e9e9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
