<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select</name>
   <tag></tag>
   <elementGuidId>27d88f89-6a30-4695-82f1-5a2e96e86ab2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Drop-Down')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Drop-Down&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f6456ea9-6949-4fc6-a4f9-927fb851f9cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card-footer-item</value>
      <webElementGuid>356a0391-996a-4819-981b-57dfe988f270</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/dropdowns</value>
      <webElementGuid>d90f8e0b-75fd-48bd-850e-3f462606e13a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Drop-Down </value>
      <webElementGuid>1c4206b6-8dcc-4507-9f8d-3c781958c900</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;has-navbar-fixed-top&quot;]/body[1]/app-root[@class=&quot;ng-tns-c490104382-0&quot;]/app-test-site[@class=&quot;ng-star-inserted&quot;]/section[@class=&quot;hero&quot;]/div[@class=&quot;hero-body&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;columns is-multiline&quot;]/div[@class=&quot;column is-3-desktop is-6-tablet ng-star-inserted&quot;]/app-menu[@class=&quot;menu-card&quot;]/div[@class=&quot;card&quot;]/footer[@class=&quot;card-footer&quot;]/a[@class=&quot;card-footer-item&quot;]</value>
      <webElementGuid>f2007291-b41c-4743-9604-f0bcc6550193</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Drop-Down')]</value>
      <webElementGuid>df400998-fef3-468d-8632-6be0824ed2a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Click'])[1]/following::a[1]</value>
      <webElementGuid>03e5380f-4928-4e34-8d29-4e6ce6bc1cdd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit'])[1]/following::a[2]</value>
      <webElementGuid>d626ea6b-7b73-4082-905f-92d505848793</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dialog'])[1]/preceding::a[1]</value>
      <webElementGuid>d0c96b90-f752-4ef5-b926-b1d45b373e3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Inner HTML'])[1]/preceding::a[2]</value>
      <webElementGuid>e37a78be-20a4-41f5-9ad0-adc9cb3f0428</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Drop-Down']/parent::*</value>
      <webElementGuid>041841ba-aa44-438c-99ed-bfb632c7c438</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/dropdowns')]</value>
      <webElementGuid>4d103927-1ce3-400a-b8b3-6b4602901eb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/app-menu/div/footer/a</value>
      <webElementGuid>9950f8d1-e97c-4e83-bb49-32769e346012</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/dropdowns' and (text() = ' Drop-Down ' or . = ' Drop-Down ')]</value>
      <webElementGuid>ad506e39-8ae8-4fa7-a90f-56cc243d88b8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
